### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by nickdesaulniers** [beaups/SamsungCID#1]
There's mixed indentation in samsung_cid.c, and [this](https://github.com/beaups/SamsungCID/blob/master/samsung_cid.c#L85-L86) could be a single return statement.

Nice work!

**Comment by beaups** [comment]
Yeah the indentation on a few of the returns don't show up that way in my editor (eclipse).  I normally don't spend much time keeping code pretty in utilities that only ever need to be used once :P
